server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul:
#http://myzuul.com:9527/microservicecloud/mydept/dept/get/1
  #ignored-services: microservicecloud-dept   #忽略单个请求
  prefix: /microservicecloud   #统一微服务请求前缀
  ignored-services: "*" #忽略所有请求
  routes:
   # 服务名之前的请求方式http://myzuul.com:9527/microservicecloud-dept/dept/get/1
    #现在需要通过zuul把服务名隐藏掉，把原先的服务名映射到/mydept/**
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

